### PR TITLE
CI/CD Setup with status badge for each branch.

### PR DESCRIPTION
**Pull request by tharnath08**

### CODE REVIEW

**Comment by corey-buchanan** [comment]
Looks good. Don't worry about it for this lab because it wasn't instructed, but you'll want to add your build folder to the .gitignore.

**Comment by tharnath08** [comment]
Made the changes @corey-buchanan . Kindly review it.

**Comment by corey-buchanan** [comment]
Nice job!

**Review by corey-buchanan — APPROVED** [review]
Approved.

**Pull request merged**
